kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: a-set-of-routing-rules-we-can-call-this-anything
  namespace: default
spec:
  hosts:
  - fleetman-staff-service.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: fleetman-staff-service.default.svc.cluster.local
        subset: safe-group
      weight: 90
    - destination:
        host: fleetman-staff-service.default.svc.cluster.local
        subset: risky-group
      weight: 10
---
kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  name: grouping-rules-for-our-photograph-canary-release
  namespace: default
spec:
  host: fleetman-staff-service.default.svc.cluster.local
  subsets:
  - labels:
      version: safe
    name: safe-group
  - labels:
      version: risky
    name: risky-group
